directories:
  directory_with_csv_xlsx: data/tabular_data
  sqldb_directory: data/sqldb.db
  directory_for_uploaded_sqldb: data/uploaded_files_sqldb.db
  stored_csv_xlsx_sqldb_directory: data/csv_xlsx_sqldb.db
  # directory_with_images: images/
  # directory_with_pdfs: pdfs/
  persist_directory: data/chroma



llm_config: 
  model_name: llama3
  embedding_model_name: all-MiniLM-L6-v2
  temperature: 0.0
  agent_llm_system_role: "Given the following user question, corresponding SQL query, and SQL result, answer the user question.\n
    Question: {question}\n
    SQL Query: {query}\n
    SQL Result: {result}\n
    Answer: 
    "
  rag_llm_system_role: "You will recieve the user's question along with the search results of that question over a database. Give the user the proper answer."



rag_config:
  collection_name: titanic_data
  top_k: 1

